### ISSUE TITLE
Tracking of players for server

### ISSUE THREAD

**Issue by willemml** [willemml/rust-mc#9]
The server should track player info such as name, uuid, health and position and attach said data to a client connection to allow for players to interact with the world.

- [x] Health, hunger, saturation
- [x] Position
- [x] Inventory
- [ ] Stats (kills, deaths, distance travelled, etc...)
- [ ] Achievements 
- [ ] Gamemode
- [ ] Saving and loading of all that player data.
- [ ] Sending the data to client
- [ ] Updating according to client actions
- [ ] Notifying clients of other players
